### ISSUE TITLE
Logging with ElasticSearch and Kibana

### ISSUE THREAD

**Issue by wellsie** [kz8s/tack#13]

**Comment by wellsie** [comment]
Beware - the addons can take some time to settle. I have seen a race between the Kibana and DNS addon, so there may be restarts on the kibana-logging-v1-xxxxx pod:

```
kubectl get pods --namespace=kube-system
NAME                                                              READY     STATUS    RESTARTS   AGE
_snip_
kibana-logging-v1-7g7be                                           1/1       Running   1          2m
_snip_
```

**Comment by ndbroadbent** [comment]
Oh cool, thanks! That's pretty much what I had set up, but I still felt like I was missing something. But that's great, I will test it out.

One thing I noticed is that elasticsearch is set up with `emptyDir`, so I guess it will lose all of it's data if the pod is unbound. Although when a container restarts, the data is still safe. But I guess this means that the elasticsearch pod can't be moved to another node (unless we were using Flocker to manage persistent storage).

Do you know if there's a way to pin a pod's containers to a specific node, so that it doesn't move around? Or is that something we don't have to worry about?

**Comment by wellsie** [comment]
This is one of the reasons why I opted for CloudWatch - durability of the log data. Several things can be done to improve this situation with ElasticSearch - like running an HA configuration. 

A quick a dirty way to pin a pod to a node is using [static pods](http://kubernetes.io/docs/admin/static-pods/). In fact I was using these before [DaemonSets](http://kubernetes.io/docs/admin/daemons/). Static pods are not as elegant an DaemonSets but could solve the issue in the short term.

Another approach that I have been meaning to investigate is creating EBS volumes which pods can mount as [awsElasticBlockStore](http://kubernetes.io/docs/user-guide/volumes/#awselasticblockstore) volumes.
