### ISSUE TITLE
Possible bug where all master instances are in the same AZ

### ISSUE THREAD

**Issue by neerfri** [kz8s/tack#21]
Hi,

first thing's first. tack is awesome!

I've noticed all my masters are placed in the same AZ:
![image](https://cloud.githubusercontent.com/assets/21379/16654053/a4e7e3ca-445c-11e6-82e6-1974fcb11ebf.png)

I believe the source of this is in the following line:
https://github.com/kz8s/tack/blob/master/modules/etcd/ec2.tf#L18
should prabably be:
`subnet_id = "${ element( split(",", var.subnet-ids), count.index ) }"`

From the [docs for the `element` function](https://www.terraform.io/docs/configuration/interpolation.html#element_list_index_):

> If the index is greater than the number of elements, this function will wrap using a standard mod algorithm

**Comment by mirthy** [comment]
I had the same problem too, I fixed in a pull request that I have open that supports existing VPCs.

**Comment by wellsie** [comment]
Thanks @neerfri - i'm really glad you like tack !!

I've deliberately kept all etcd instances in one AZ, until now, because I have not yet had a chance to investigate how raft and etcd behave across AZs. It most likely will be fine, but I would like to run some experiments first.

I will spend some time this week digging more into this.

For reference:
https://github.com/kubernetes/kubernetes/issues/13056

**Comment by wellsie** [comment]
running *all* instances in single az now by default
